#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

git config --global user.name "hugo-adword"
git config --global user.email "00.hugo.ad@gmail.com"
# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init -q --no-repo-verify --depth=1 -u git://github.com/DerpFest-11/manifest.git -b 11 -g default,-device,-mips,-darwin,-notdefault

# Clone local manifest! So that no need to manually git clone repos or change hals, you can use normal git clone or rm and re clone, they will cost little more time, and you may get timeout! Let's make it quit and depth=1 too.
# will setup later

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8

#device
git clone https://github.com/adnan-44/device_xiaomi_vince --single-branch -b for-me device/xiaomi/vince
git clone https://github.com/adnan-44/vendor_xiaomi_vince --single-branch -b derp-11 vendor/xiaomi/vince --depth 1
git clone https://github.com/Blacksuan19/kernel_dark_ages_vince.git --single-branch -b darky kernel/xiaomi/vince
rm -rf hardware/qcom-caf/wlan && git clone https://android.googlesource.com/platform/hardware/qcom/wlan hardware/qcom-caf/wlan

# Hal
rm -rf hardware/qcom-caf/msm8996
git clone https://gitlab.com/hugo-adword/hardware_qcom_audio.git --single-branch -b r11.0 hardware/qcom-caf/msm8996/audio
git clone https://gitlab.com/hugo-adword/hardware_qcom_display.git --single-branch -b r11.0 hardware/qcom-caf/msm8996/display
git clone https://gitlab.com/hugo-adword/hardware_qcom_media.git --single-branch -b r11.0 hardware/qcom-caf/msm8996/media

cd kernel/xiaomi/vince && git revert fec013b9f5bb70c1e51285aa6e042f21f4298447 --no-edit && cd ../../.. 
